@startuml

class Employee {
    - firstName: String
    - lastName: String
    - salary: String
    + setFirstName(String fName): void
    + setLastName(String lName): void
    + setSalary(String salary): void
    + getFirstName(): String
    + getLastName(): String
    + getSalary(): String
}


class Parser {
    -readFromFile(String fileName): List
    +parseInput(String fileName): List
    +printList(list): void
}


class Application {
    main()
    new Parser();
}

Application -- Parser

Parser ..o Employee
@enduml