@startuml

class Application {
main()
WebsiteCreator web
'object of WebsiteCreator web constructed
'web.createWebsite() does the rest
}

class Website {
//Website defined as a record
-siteName: String
-author: String
-makeJavaDir: boolean
-makeCssDir : boolean

+getSiteName(): String
+getAuthor(): String
+getMakeJavaDir(): boolean
+getMakeCssDir(): boolean
}

class WebsiteCreator {
    //methods can throw IO Exceptions
    +getUserInput(): Website
    -writeToHTML(String fileName, Website userFile): void
    +createWebsite(): void
}
Application ..o WebsiteCreator
WebsiteCreator --o Website

@enduml