@startuml

class Sorter {
    -inFileName: String

    +readFile(): ArrayList<String>
    +alphabetSortList(ArrayList<String> list): ArrayList<String>
    +printToFile(ArrayList<String> list)): void
}


class Application {
    nameList: ArrayList<String>
}

class ListPrinter {
    -outFileName: String
    +printToFile(ArrayList<String> list)): File
}

Application .. Sorter
Sorter .. ListPrinter

@enduml